services:
  meemo:
    build: .
    image: on195594/meemo:local
    container_name: meemo
    volumes:
      - ./users.json:/app/data/.users.json
      - ./data:/app/data/storage
    environment:
      - CLOUDRON_MONGODB_URL=mongodb://mongodb:27017/meemo
      - CLOUDRON_APP_ORIGIN=http://localhost:3000
      - CLOUDRON_LOCAL_AUTH_FILE=/app/data/.users.json
      - ATTACHMENT_DIR=/app/data/storage
    ports:
      - 3000:3000/tcp
    depends_on:
      - mongodb
    networks:
      - backend
    restart: always
  mongodb:
    image: mongo:5.0.20
    container_name: meemo_mongo
    volumes:
      - ./database:/data/db
    networks:
      - backend
    restart: always

networks:
  backend:
    driver: bridge
